# Generated by Django 4.2.5 on 2023-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Gujarat', 'Gujarat'), ('Rajasthan', 'Rajasthan'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhara pradesh', 'Andhara pradesh'), ('Arunachal pradesh', 'Arunachal pradesh'), ('Bihar', 'bihar'), ('Chandigarh', 'chandigarh'), ('Dadra & Nagar Hveli', 'Dadara & Nagae Haveli'), ('west bengal', 'west bengal')], max_length=50),
        ),
    ]
